### PR TITLE
Updated and Fixed code, Created a Input Mapper GUI.

### PR DESCRIPTION
**Pull request by CallumCarmicheal**
I have been working on this for a few weeks now, decided might aswell
fix some features if im going to use it.

+ Reworked mouse movement code so that it is more smoother (50/50
Experience)
+ Revisted the Graphical User Interface
+ Created configurations
+ Created a Input Mapper (Mouse is TODO.)
+ Created a Live Preview of controls (Not fully finished)
+ Changed it so you dont have to run the Xbox window in fullscreen (Good
to see the controls while gamimg)
+ Set the controller to be reset when being detached.
+ Set a custom detach key
+ Some more not said here...

Screenshot of the modified gui

### CODE REVIEW

**Comment by fqlx** [comment]
Delete the precompiled .exe (for security reasons), I'll merge, and then upload a precompiled .exe.
Good work by the way!

**Comment by CallumCarmicheal** [comment]
I deleted both of the files so you could recompile them and thanks - I have no idea how to do the controller emulation and decided to help out on this hidden gem :D also good work!

**Comment by fqlx** [comment]
Will upload the compiled .exe tonight.  Thanks for the help!

**Comment by CallumCarmicheal** [comment]
Anytime this is a good project with the only problem of making a smooth/fluid mouse movement.

**Pull request merged**
